# Docs: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 8 # note that this is _per-file_
    directory: "/"
    pull-request-branch-name:
      # so it's compatible with docker tags
      separator: "-"